# This is your sidebar TOC. The sidebar code loops through sections here and provides the appropriate formatting.


entries:
- title: Sidebar
  #product: Collectors
  #version: 1.0
  folders:

  - title:
    output: pdf
    type: frontmatter
    folderitems:
    - title:
      url: /titlepage
      output: pdf
      type: frontmatter
    - title:
      url: /tocpage
      output: pdf
      type: frontmatter

  - title: Getting Started
    output: web, pdf
    folderitems:
    - title: All Collectors
      url: /p1_landing_page.html
      output: web

    - title: SCM Collectors
      #url: /p1_sample1.html
      output: web, pdf

    - title: Feature Collectors
      #url: /p1_sample2.html
      output: web, pdf

    - title: Build Collectors
      #url: /p1_sample3.html
      output: web, pdf
      
    - title: Deployment Collectors
      #url: /p1_sample3.html
      output: web, pdf
      
    - title: Communication Collectors
      #url: /p1_sample3.html
      output: web, pdf

 # - title: Another heading
 #   output: web, pdf

 #   folderitems:
 #   - title: Sample 4
 #     url: /p1_sample4.html
 #     output: web, pdf

 #   - title: Sample 5
 #     url: /p1_sample5.html
 #     output: web, pdf

 #   - title: Sample 6
 #     url: /p1_sample6.html
 #     output: web, pdf

 #   - title: Sample 7
 #     url: /p1_sample7.html
 #     output: web, pdf
