# This is your sidebar TOC. The sidebar code loops through sections here and provides the appropriate formatting.

entries:
- title: sidebar
  #product: 
  #version: 
  folders:
  - title:
    output: pdf
    type: frontmatter
    folderitems:
    - title:
      url: /titlepage
      output: pdf
      type: frontmatter
    - title:
      url: /tocpage
      output: pdf
      type: frontmatter
  
  - title: Introduction
    output: web, pdf
    folderitems:
    - title: Overview
      url: /Introduction.html
      output: web, pdf
      type: homepage
      
  - title: Signup and Login
    output: web, pdf
    folderitems:
    - title: Admin User
      url: signup.html
      output: web, pdf
    - title: Other Users
      url: user_signup.html
      output: web, pdf
          
  - title: Select your Dashboard
    output: web, pdf
    folderitems:
    - title: Selecting Dashboards
      url: select_dashboard.html
      output: web, pdf
      
  - title: The Team Dashboard
    output: web, pdf
    folderitems:
    - title: Introduction
      url: team_dashboard_intro.html
      output: web, pdf
    - title: Create a Team Dashboard
      url: create_team_dashboard.html
      output: web, pdf
    - title: Widget View
      url: widget_view.html
      output: web, pdf
    - title: Dashboard Gamification
      url: keeping_score.html
      output: web, pdf
    - title: Pipeline View
      url: pipeline_view.html
      output: web, pdf
    - title: Cloud View
      url: cloud_view.html
      output: web, pdf  
  
  - title: The Product Dashboard
    output: web, pdf
    folderitems:
    - title: Introduction
      url: product_dashboard_intro.html
      output: web, pdf  
    - title: Create a Product Dashboard
      url: product_view.html
      output: web, pdf

  - title: Administer your Dashboard
    output: web, pdf
    folderitems:
    - title: Dashboard Administration
      url: dashboard_administration.html
      output: web, pdf
    