# kickstart travis.
language: java

# need to override travis 'install' since it will try gpg sign and fail.
install: mvn clean compile install package -Dmaven.repo.local=$TRAVIS_BUILD_DIR/.maven/repo -DskipTests=true
