# kickstart travis.
language: java

install: mvn install -DskipTests=true

# need to override travis 'install' since it will try gpg sign and fail.
install: mvn clean compile package -DskipTests=true
