# kickstart travis.
language: java

notifications:
  webhooks:
    urls:
      https://webhooks.gitter.im/e/48597b0f75dd571734bc
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always

# need to override travis 'install' since it will try gpg sign and fail.
#install: mvn clean compile package -DskipTests=true
