language: java
jdk:
- oraclejdk8
script:
  - ./gradlew clean check
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a16b5d488f83a21fda99
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
