# Help: rename the adject docker-compose.override.example.yml file to docker-compose.override.yml
#       then in the override file uncomment the environment tag for the collectors you want to
#       run. Then add the environment vars you want to use.
version: '3'
services:
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - "db-data:/data/db"

  db-setup:
    build: db
    depends_on:
      - db

  api:
    # build: api
    image: hygieia-api
    depends_on:
      - db-setup
    ports:
      - "8080:8080"

  ui:
    # build: UI
    image: hygieia-ui
    depends_on:
      - api
    ports:
      - "3000:80"

  appdynamics-collector:
    # build: collectors/performance/appdynamics
    image: hygieia_appdynamics_collector
    depends_on:
      - db-setup

  artifactory-artifact-collector:
    # build: collectors/artifact/artifactory
    image: hygieia_artifactory_collector
    depends_on:
      - db-setup

  bitbucket-collector:
    # build: collectors/scm/bitbucket
    image: hygieia_bitbucket_collector
    depends_on:
      - db-setup

  chat-ops-collector:
    # build: collectors/misc/chat-ops
    image: hygieia_chatops_collector
    depends_on:
      - db-setup

  github-collector:
    # build: collectors/scm/github
    image: hygieia_github_collector
    depends_on:
      - db-setup

  jenkins-build-collector:
    # build: collectors/build/jenkins
    image: hygieia_jenkins_collector
    depends_on:
      - db-setup

  jenkins-cucumber-test-collector:
    # build: collectors/build/jenkins-cucumber
    image: hygieia_jenkins_cucumber_collector
    depends_on:
      - db-setup

  jira-collector:
    # build: collectors/feature/jira
    image: hygieia_jira_collector
    depends_on:
      - db-setup

  sonar-codequality-collector:
  #  build: collectors/build/sonar
    image: hygieia_sonar_collector
    depends_on:
      - db-setup

  subversion-collector:
    # build: collectors/scm/subversion
    image: hygieia_subversion_collector
    depends_on:
      - db-setup

  udeploy-collector:
    # build: collectors/deploy/udeploy
    image: hygieia_udeploy_collector
    depends_on:
      - db-setup

  versionone-collector:
    # build: collectors/feature/versionone
    image: hygieia_versionone_collector
    depends_on:
      - db-setup

  xldeploy-collector:
    # build: collectors/deploy/xldeploy
    image: hygieia_xldeploy_collector
    depends_on:
      - db-setup

volumes:
  db-data:
