version: '3'
services:
  api:
    # environment: # for a full list check the corresponding properties-builder file
    #   - DB_DATABASE: dashboarddb
    #   - DB_HOST: db
    #   - DB_PORT: 27017
    #   - DB_USERNAME: dashboarduser
    #   - DB_PASSWORD: dbpassword
    # volumes:
    #   - ./logs:/hygieia/logs

  ui:
    # environment:

  appdynamics-collector:
    # environment:

  artifactory-artifact-collector:
    # environment:

  bitbucket-collector:
    # environment:

  chat-ops-collector:
    # environment:

  github-collector:
    # environment:

  jenkins-build-collector:
    # environment:

  jenkins-cucumber-test-collector:
    # environment:

  jira-collector:
    # environment:

  sonar-codequality-collector:
    # environment:

  subversion-collector:
    # environment:

  udeploy-collector:
    # environment:

  versionone-collector:
    # environment:

  xldeploy-collector:
    # environment:
