version: '2'
services:
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - "db-data:/data/db"

  db-setup:
    build: db
    depends_on:
      - db
    links:
      - db:db

  api:
    image: hygieia-api
    depends_on:
      - db-setup
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/hygieia/logs
    links:
      - db:db

  hygieia-ui:
    image: hygieia-ui
    depends_on:
      - api
    ports:
      - "3000:80"
    links:
      - api:api
volumes:
  db-data:
