package com.capitalone.dashboard.model;

import java.util.ArrayList;
import java.util.Collection;

import lombok.Data;

@Data
public class TestCapability {

    /**
     * Creation timestamp
     */
    private long timestamp;

    /**
     * Identifies this test result in the source system
     */
    private String executionId;

    /**
     * Description of the test result that might make sense to a human
     */
    private String description;

    /**
     * Optional URL to test results
     */
    private String url;

    /**
     * Start test execution time {@link java.util.Date#getTime()}
     */
    private long startTime;

    /**
     * End test execution time {@link java.util.Date#getTime()}
     */
    private long endTime;

    /**
     * Test duration in milliseconds
     */
    private long duration;

    /**
     * Count of test cases that failed in all test suites
     */
    private int failedTestSuiteCount;

    /**
     * Count of test cases that generated an error in all test suites
     */
    private int successTestSuiteCount;

    /**
     * Count of test cases that were skipped in all test suites
     */
    private int skippedTestSuiteCount;

    /**
     * The total number of test cases in all test suites
     */
    private int totalTestSuiteCount;

    private int unknownStatusTestSuiteCount;

    private TestCaseStatus status;

    /**
     * Type of test
     */
    private TestSuiteType type;


    /**
     * Collection of {@link TestSuite}s generated by this TestResult.
     */
    private Collection<TestSuite> testSuites = new ArrayList<>();
}
