#!/bin/bash
#set -x
docker build -t hygieia .
if [ $? -ne 0 ]
then
  exit
fi
# enable if you have a registry running
#docker tag -f hygieia localhost:5000/peter/hygieia:1.1

# Find and stop running image with name Hygieia
RUNNINGIMAGE=`docker ps|grep hygieia|awk -F\  '{print $1}'`
if [ "$RUNNINGIMAGE" != "" ]
then
  docker stop $RUNNINGIMAGE
fi

# Find stopped image with name Hygieia
STOPPEDIMAGE=`docker ps -a|grep hygieia|awk -F\  '{print $1}'`
if [ "$STOPPEDIMAGE" != "" ]
then
  docker rm hygieia
fi

ID=`docker run -d --publish 3000:3000 --publish 3001:80 --env TZ="Europe/Amsterdam" --name hygieia --hostname hygieia -v /root/docker/mongodb:/data hygieia`
# enable if you have a registry running
#ID=`docker run -d --publish 3000:3000 --env TZ="Europe/Amsterdam" --name hygieia --hostname hygieia -v /root/docker/mongodb:/data localhost:5000/peter/hygieia:1.1`
docker exec -ti $ID bash
