package com.capitalone.dashboard.uitest.utils;

import java.util.Scanner;

import com.capitalone.dashboard.util.Encryption;
import com.capitalone.dashboard.util.EncryptionException;

public class EncryptionHelper {

	public static void main(String args[]) throws EncryptionException {
		Scanner scanner = new Scanner(System.in);
		
		System.out.println("The EncryptionHelper uses a key that is generated by the Encryption class in the Hygieia core project.");
		System.out.println("The UI-tests project assumes only one encryption key exists, and that it is passed in as a -D arg when ran through maven.");
		System.out.println("DO NOT SAVE CREDENTIALS WITH MULTIPLE ENCRYPTION KEYS! THIS WILL CAUSE UNDESIREABLE BEHAVIOR!");
		System.out.println("If you do not already have an encryption key, please save this one and share it with your dev team.");
		System.out.println(Encryption.getStringKey());
		System.out.println();
		System.out.println("Enter your encryption key:");
		
		String key = scanner.nextLine();
		
		System.out.println("Enter your string to encrypt:");
		String toEncrypt = scanner.nextLine();
		
		String encrypted = Encryption.encryptString(toEncrypt, key);
		
		System.out.println("Encrypted string:");
		System.out.println(encrypted);
		
		System.out.println();
		
		System.out.println("Decrypting to show backwards compatibility:");
		System.out.println(Encryption.decryptString(encrypted, key));
		
		scanner.close();
	}
	
}
