apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: db
  name: db
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - env:
        - name: MONGODB_DATABASE
          value: dashboarddb
        - name: MONGODB_PASSWORD
          value: dbpassword
        - name: MONGODB_USERNAME
          value: dashboarduser
        image: japm/mongodb:latest
        name: db
        ports:
        - containerPort: 27017
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: db
  name: db
spec:
  ports:
  - name: "27017"
    port: 27017
    targetPort: 27017
  selector:
    app: db
