apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: jenkins-build-collector
  name: jenkins-build-collector
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: jenkins-build-collector
    spec:
      containers:
      - env:
        - name: JENKINS_API_KEY
          value: 17072cb8cc3e5b1b94a4f2d4cc442acf
        - name: JENKINS_CRON
          value: 0 * * * * *
        - name: JENKINS_MASTER
          value: https://alm-latam.accenture.com/fs-rec-brdsco-jenkins
        - name: JENKINS_USERNAME
          value: admin
        - name: MONGO_PORT
          value: tcp://db:27017
        image: ikarofsantos/hygieia-jenkins-build-collector
        name: jenkins-build-collector
      restartPolicy: Always
