apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: phabricator-collector
  name: phabricator-collector
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: phabricator-collector
    spec:
      containers:
      - env:
        - name: MONGO_PORT
          value: tcp://db:27017
        - name: PHABRICATOR_HOST
          value: <<address>
        - name: PHABRICATOR_TOKEN
          value: <<token>>
        image: japm/hygieia-phabricator-scm-collector
        name: phabricator-collector
      restartPolicy: Always
