package com.capitalone.dashboard.status;

public enum CodeQualityAuditStatus {
    CODE_QUALITY_AUDIT_FAIL,
    STATIC_SECURITY_SCAN_FAIL,
    CODE_QUALITY_AUDIT_GATE_MISSING,
    QUALITY_PROFILE_VALIDATION_AUDIT_OK,
    QUALITY_PROFILE_VALIDATION_AUDIT_FAIL,
    QUALITY_PROFILE_VALIDATION_AUDIT_NO_CHANGE,
    CODE_QUALITY_DETAIL_MISSING, CODE_QUALITY_AUDIT_OK,
    STATIC_SECURITY_SCAN_AUDIT_NO_CHANGE,
    STATIC_SECURITY_SCAN_MISSING,STATIC_SECURITY_SCAN_OK,STATIC_SECURITY_SCAN_NO_CLOSED_FINDINGS,
    STATIC_SECURITY_SCAN_FOUND_CRITICAL,STATIC_SECURITY_SCAN_FOUND_HIGH,
    COLLECTOR_ITEM_ERROR,
    CODE_QUALITY_NOT_CONFIGURED
}
