package com.capitalone.dashboard.status;

public enum CodeQualityAuditStatus {
    CODE_QUALITY_AUDIT_FAIL,
    CODE_QUALITY_AUDIT_GATE_MISSING,
    QUALITY_PROFILE_VALIDATION_AUDIT_OK,
    QUALITY_PROFILE_VALIDATION_AUDIT_FAIL,
    QUALITY_PROFILE_VALIDATION_AUDIT_NO_CHANGE,
    CODE_QUALITY_DETAIL_MISSING, CODE_QUALITY_AUDIT_OK
}
