package com.capitalone.dashboard.status;

public enum TestResultAuditStatus {
    TEST_RESULT_AUDIT_FAIL,
    TEST_RESULT_AUDIT_MISSING,
    TEST_RESULT_MISSING,
    TEST_RESULT_AUDIT_OK,
    TEST_RESULTS_TRACEABILITY_NOT_FOUND,
    TEST_RESULTS_TRACEABILITY_STORY_NOT_FOUND,
    TEST_RESULTS_TRACEABILITY_STORY_MATCH,
    TEST_RESULTS_TRACEABILITY_THRESHOLD_DEFAULT,
    TEST_RESULTS_TRACEABILITY_STORY_STATUS_INVALID,
    TEST_RESULTS_TRACEABILITY_NOT_FOUND_IN_GIVEN_DATE_RANGE
}
